package com.omeryildizce.collections

fun main() {
    val meyveler =  ArrayList<String>()
    meyveler.add("Çilek")
    meyveler.add("Muz")
    meyveler.add("Elma")
    meyveler.add("Kivi")
    meyveler.add("Kiraz")
    meyveler.add("Karpuz")
    println(meyveler.isEmpty())
    println(meyveler.count())
    println(meyveler.size)
    println(meyveler.first())
    println(meyveler.last())
    println(meyveler.indices)
    println(meyveler.contains("Muz"))
    println(meyveler.max())
    println(meyveler.min())
    meyveler
    println(meyveler.toString())
    meyveler.reverse()
    println(meyveler.toString())
    meyveler.removeAt(3)
    println(meyveler.toString())
    meyveler.remove("Muz")
    println(meyveler.toString())
    meyveler.clear()
    println(meyveler.toString())
}